title: OpenCloudHub
description: MLOps platform on Kubernetes - Master's thesis project demonstrating enterprise-grade machine learning lifecycle management
theme: just-the-docs
url: "https://docs.opencloudhub.org"
aux_links:
  "GitHub": "https://github.com/OpenCloudHub"
aux_links_new_tab: true
logo: "/assets/images/primary-logo-light.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: opencloudhub
nav_sort: case_insensitive

callouts:
  warning:
    title: Warning
    color: orange
  highlight:
    title: Highlight
    color: teal
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: red